version: "3.9"

# Run: docker compose -f docker-chat.monitoring.yml up -d

services:
  redis:
    image: redis:alpine
    container_name: redis-chat
    ports:
      - "6380:6379"
    volumes:
      - redis_data:/data

  mongodb:
    image: mongo:6
    container_name: mongodb-chat
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
    volumes:
      - mongodb_data:/data/db

  qdrant:
    image: qdrant/qdrant
    container_name: qdrant-chat
    ports:
      - "6333:6333"
      - "6334:6334"
    volumes:
      - qdrant_data:/qdrant/storage

volumes:
  redis_data:
  mongodb_data:
  qdrant_data: